### ISSUE TITLE
[EPIC] Eventing Auth Manager 

### ISSUE THREAD

**Issue by strekm** [kyma-project/eventing-auth-manager#1]
**Description**

The `eventing` component is exposing an endpoint using a `APIRule` of type `oauth2_introspection` and securing it with ORY Hydra `oauth2client`. ORY Hydra is a deprecated component in Kyma. 
A new kyma module `Eventing Auth Manager` should provide equivalent functionality as implemented using ORY Hydra `oauth2client`. 
This component should be a **central** component deployed on **control-plane**. It uses credentials for [IAS (identity authentication service)](https://help.sap.com/docs/identity-authentication?locale=en-US) - accessible on the control plane - to manage apps. The controller should be watching `kyma` resources. When Kyma is provisioned the controller should create a new IAS app for this Kyma instance. 
Controller should create EventingAuth resource with owner reference to Kyma (Kyma deletion triggers EventingAuth deletion).
The IAS app must be easily identifiable by the runtime ID of the `kyma` cluster. The application should have `SSO` type configured to `OIDC`. 

Then controller should create a new secret on the kyma cluster within the newly created application. The secret contains the retrieved data: 
- client id, 
- client secret 
- token url. 
 
This secret is then used by eventing to replace the secret previously provided by ORY. The credentials will be used to configure webhooks on EventMesh. 

![eventingauthmanagersetup](https://user-images.githubusercontent.com/292906/230387760-8392eee5-f304-46fe-bed5-1e6b456677b5.png)

![flow](https://user-images.githubusercontent.com/292906/230390736-bda5c375-99d7-4f25-bd77-7e74f81a2e47.png)

TODOs:
- [x] POC on XSUAA vs IAS
- [x] POC IAS API
- [x] perf tests of IAS 
- [x] [implement controller creating IAS app and secret and persisting data on kyma runtime](https://github.com/kyma-project/eventing-auth-manager/issues/2)
- [x] [Kyma CR watcher](https://github.com/kyma-project/eventing-auth-manager/issues/13)
- [x] implement deletion of IAS app
- [x] documentation
- [x] #20
- [x] #23
- [x] #21
- [x] threat modelling
- [x] #32
- [x] #33

**Reasons**

Removing ORY Hydra dependency from eventing component
