### ISSUE TITLE
On-call Documentation

### ISSUE THREAD

**Issue by grischperl** [kyma-project/eventing-auth-manager#33]
**Description**
Write the on-call documentation for the Eventing Auth Manager to be prepared for the roll-out to production

**Tasks**
- [x] What does it do? (resources etc to look at; use other on-call docu as a guideline)
- [x] How to access the IAS application using the web interface (credentials etc)
- [x] Possible fail scenario: SKR kubeconfig may not be there to access another cluster
- [ ] ~~[How to update existing secrets created by the eventing auth manager on Dev/Stage/Prod](https://github.com/orgs/kyma-project/projects/17/views/12?pane=issue&itemId=31254930)~~ (Note: not needed here).
